### PR TITLE
Adding logo

### PR DESCRIPTION
**Pull request by CsatariGergely**
Logo variants and formats and a logo displayed in README.md

### CODE REVIEW

**Comment by iakkus** [comment]
Hi @CsatariGergely , thanks for the PR!

Could you update the files according to the [slack discussion](https://knix.slack.com/archives/C011XA52JHG/p1600763677007900)?

**Review by iakkus — CHANGES_REQUESTED** [review]
Hi @CsatariGergely , thanks for the PR!

Could you update the files according to the [slack discussion](https://knix.slack.com/archives/C011XA52JHG/p1600763677007900)?

**Comment by CsatariGergely** [comment]
> 
> 
> Hi @CsatariGergely , thanks for the PR!
> 
> Could you update the files according to the [slack discussion](https://knix.slack.com/archives/C011XA52JHG/p1600763677007900)?

@iakkus  Done. Please check.

**Review by iakkus — CHANGES_REQUESTED** [review]
Looks great, thanks!

Would it be also possible to add the '.svg' versions for the 'bw' files?

**Review by manuelstein — APPROVED** [review]
LGTM

**Comment by iakkus** [comment]
I guess we can always add the *.svg versions of the bw logos.

**Pull request merged**
