### PR TITLE
Feature/individual indices for workflow logs

### LINKED ISSUE #25: deletion of workflow logs
[Environment]: bare metal, Kubernetes
[Known affected releases]: master (includes all releases)

Currently, the workflow logs are never deleted. clearAllWorkflowLogs function in the management service is still a placeholder (#24). 

Deletion of workflow logs would be desired for many reasons:
1. storage space reduction (periodically)
2. privacy implications (e.g., deletion of a user accounts, #5)
3. user-desired actions (e.g., debugging workflows)

Possible solutions include: 
1. Deletion of individual logs (on-demand)
2. Periodical deletion of old logs (e.g., remove logs after 30 days)

It seems like we have a single index for all workflow output, which makes it difficult for solution 1 to be implemented. (@paarijaat: is this correct?) Searching individual entries and deleting them seems like it might cause performance issues (https://discuss.elastic.co/t/delete-logs-in-elasticsearch-after-certain-period/75067/17). To solve this problem, we can change the logging indices, so that each workflow gets its own index.

As for solution 2, ElasticSearch has a component Curator that can be utilized as such. Others have also implemented their own (e.g., https://blog.chesterwood.io/2019/06/how-to-delete-old-elasticsearch-logs.html).

@paarijaat : What do you think?

### PR DESCRIPTION
**Pull request by iakkus**
- Create individual workflow indices for logging, such that it is easier to delete them when the workflow is deleted or the account is deleted
- Clear workflow logs by deleting and recreating the index

Fixes #25.

### CODE REVIEW

**Comment by ruichuan** [comment]
All changes look good to me technically.  Just one question: do we really want to clear the associated logs once the workflows or users are deleted?  Suppose a user did something malicious and then deleted his account, we'd not be able to figure out what went wrong if the associated logs also got cleared.

**Comment by iakkus** [comment]
Well, even if we disable that, the user can just delete the logs first and then delete the account.

Another way is to set a timestamp for the workflow when there is a clearing request, and return the logs after that timestamp when requested. 

However, that will just mean we keep the logs forever until somebody somehow deletes them. We don't have a clear solution for that either. 

Not sure which is the better way.

**Comment by ruichuan** [comment]
Yeah, maybe generating a timestamp to the logs when the associated
workflows/users get deleted.  Then, there is a retention period after which
the logs could be really deleted.

**Comment by iakkus** [comment]
Which component would be responsible for checking these workflows and actually deleting their logs? How do we enforce the retention period then?

**Comment by paarijaat** [comment]
Changes look fine to me.

We are only deleting logs that are generated as a result of print statements inside user code (and very few print statements of the function worker instance). It is  not clear what malicious intent could/should be inferred by those logs.  We are in any case not deleting interaction of the user's workflow with the management service (that is the management service logs of a user). We are also not deleting the fronted logs of a workflow. So we have those logs as well and maybe we should delete them too?

**Comment by iakkus** [comment]
I think maintaining the "management service logs concerning a user" should be fine, because it actually tells us the story of what that particular user is doing. Besides that, I agree that deleting the user's logs should be okay, because their content is less indicative of the the system's operation.

As for the frontend logs of that service, I think keeping is also fine, because the frontend is part of the platform. Just like we should keep the DataLayerService or nginx logs concerning that user's workflows.

In that regard, I think we can leave this as it is. If that's okay with both of you, we can merge this.

**Comment by ruichuan** [comment]
Yes, I'm okay with this setting.  Thanks!

**Pull request merged**
