### PR TITLE
Feature/asl sf state names

### PR DESCRIPTION
**Pull request by ksatzke**
[Environment]: Kubernetes, bare metal
[Known affected releases]: master (includes all releases)

Currently, whenever an ASL workflow description state name (not resource name) contains whitespaces (for an example, see: https://aws.amazon.com/getting-started/hands-on/create-a-serverless-workflow-step-functions-lambda/?nc1=h_ls), it cannot be deployed to KNIX. 

However, Amazon state language does allow such state names. This fix allows for successful deployment and execution of ASL workflows with state names containing white spaces on KNIX.

### CODE REVIEW

**Comment by iakkus** [comment]
Thanks for the PR!

1) Could you take another look at the debug related print/log statements and remove the irrelevant ones?
2) The fix and the test case seem to be relevant to only whitespace in state names. How about the other special characters described in issue #39? Do they work? If not, I think those fixes should also be included in this PR.
3) Can you rename the test case to reflect that (maybe "asl_State_Names_with_Special_Chars")?

**Comment by ksatzke** [comment]
Thanks for your comments! Actually, the characters mentioned also work, so I've added another test case on that. Also cleaned up debug related info, and renamed test case.

**Comment by iakkus** [comment]
Fixes #51.

**Comment by iakkus** [comment]
Fixes #39.

**Pull request merged**
