### PR TITLE
Riak start script

### PR DESCRIPTION
**Pull request by ruichuan**
This branch is to stabilize the riak start script via adding retries and reporting errors when the cluster is started unsuccessfully.

### CODE REVIEW

**Comment by iakkus** [comment]
Should we also add some reachability related checks? 
The 'curl' statement currently fails in a silent way and I think someone had run into this issue. Maybe we can also retry on that?

**Comment by ruichuan** [comment]
I think the 'valid' check towards the end does a similar thing.

**Comment by ruichuan** [comment]
> Should we also add some reachability related checks?
> The 'curl' statement currently fails in a silent way and I think someone had run into this issue. Maybe we can also retry on that?

The retry for reachability check has been added.

**Comment by ruichuan** [comment]
I thought the "riak-admin cluster join" succeeds only if it has
successfully marked a node as "joining".  But, I guess it does no harm if
we add a sleep before that "joining" check.  Pushed a simple change.
Thanks.

**Pull request merged**
